prometheus:
  kube-state-metrics:
    enabled: true
    releaseLabel: true
    metricLabelsAllowlist:
      - pods=[*]
      - nodes=[topology.kubernetes.io/region,node.kubernetes.io/instance-type,kubernetes.io/os]
    metricAnnotationsAllowList: []
    collectorsExclude:
      - secrets
      - configmaps

  prometheus-node-exporter:
    enabled: true
    hostNetwork: false

  prometheus-pushgateway:
    enabled: false

  alertmanager:
    enabled: false

  server:
    remote_write:
    # OptScale target. Includes auth, TLS and metric filter
    - url: https://my.optscale.com/storage/api/v2/write
      name: optscale

    # OptScale Kubernetes data source id
    dataSourceId: null
    # Username which is used on OptScale Kubernetes data source registration
    username: null
    # Password which is used on OptScale Kubernetes data source registration
    password: null
    # Remote write OptScale target TLS CA certificate file (leave empty to use system trust store)
    caFile:
    # Set to true only for self-hosted OptScale with a self-signed certificate
    insecure_skip_verify: false

    configMapOverrideName: prometheus-server-config
    persistentVolume:
      enabled: false
    defaultFlagsOverride:
    - --enable-feature=agent
    - --config.file=/etc/config/prometheus.yml
    - --web.enable-lifecycle
    extraConfigmapMounts:
    # ConfigMap with CA cert file
    - name: cert-config
      mountPath: /etc/optscale/ssl
      configMap: prometheus-server-cert-config
      subPath: ""
      readOnly: true
    extraSecretMounts:
    # Secret with password file
    - name: password-secret
      mountPath: /etc/optscale/auth
      subPath: ""
      secretName: prometheus-server-password-secret
      readOnly: true

  serverFiles:
    prometheus.yml:
      rule_files: []
      scrape_configs:
        - job_name: kubernetes-nodes-cadvisor
          scheme: https
          tls_config:
            ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            insecure_skip_verify: true
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          kubernetes_sd_configs:
            - role: node
          relabel_configs:
            - action: labelmap
              regex: __meta_kubernetes_node_label_(.+)
            - target_label: __metrics_path__
              replacement: /metrics/cadvisor

        - job_name: kube-state-metrics
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                own_namespace: true
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              regex: kube-state-metrics
              action: keep
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              regex: http
              action: keep

        - job_name: prometheus-node-exporter
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                own_namespace: true
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              regex: prometheus-node-exporter
              action: keep
            - source_labels: [__meta_kubernetes_pod_node_name]
              target_label: node

        - job_name: kube-service-selectors
          kubernetes_sd_configs:
            - role: endpoints
              namespaces:
                own_namespace: true
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              regex: kube-service-selectors
              action: keep
