prometheus:
  kube-state-metrics:
    releaseLabel: true
    metricLabelsAllowlist:
      - endpoints=[*]
      - jobs=[*]
      - namespaces=[*]
      - nodes=[*]
      - pods=[*]
      - services=[*]
    metricAnnotationsAllowList:
      - endpoints=[*]
      - jobs=[*]
      - namespaces=[*]
      - nodes=[*]
      - pods=[*]
      - services=[*]

  serviceAccounts:
    alertmanager:
      create: false

  kubeStateMetrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true
    hostNetwork: false

  prometheus-pushgateway:
    enabled: true
    persistentVolume:
      enabled: false

  alertmanager:
    enabled: false

  server:
    remote_write:
    # OptScale target skeleton. Target also includes tls and auth settings, extra headers and so on
    - url: https://my.optscale.com/storage/api/v2/write
      name: optscale

    # OptScale Kubernetes data source id
    dataSourceId: null
    # Username which is used on OptScale Kubernetes data source registration
    username: null
    # Password which is used on OptScale Kubernetes data source registration
    password: null
    # Remote write OptScale target tls CA certificate file
    caFile:

    configMapOverrideName: prometheus-server-config
    persistentVolume:
      enabled: false
    defaultFlagsOverride:
    - --enable-feature=agent
    - --config.file=/etc/config/prometheus.yml
    - --web.enable-lifecycle
    extraConfigmapMounts:
    # Config map with CA cert file
    - name: cert-config
      mountPath: /etc/optscale/ssl
      configMap: prometheus-server-cert-config
      subPath: ""
      readOnly: true
    extraSecretMounts:
    # Secret with password file
    - name: password-secret
      mountPath: /etc/optscale/auth
      subPath: ""
      secretName: prometheus-server-password-secret
      readOnly: true
  serverFiles:
    prometheus.yml:
      rule_files: []

