apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-service-selectors.fullname" . }}
  namespace: {{ template "kube-service-selectors.namespace" . }}
  labels:
    {{- include "kube-service-selectors.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kube-service-selectors.selectorLabels" . | indent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kube-service-selectors.selectorLabels" . | indent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kube-service-selectors.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- if .Values.extraArgs }}
          {{- range .Values.extraArgs }}
          - {{ . }}
          {{- end }}
          {{- end }}
          {{- if .Values.service.port }}
          - --port={{ .Values.service.port | default 30091 }}
          {{- end }}
          {{- if .Values.namespaces }}
          - --namespaces={{ .Values.namespaces }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port | default 30091 }}
              name: "http"
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port | default 30091 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
