apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-service-selectors.fullname" . }}
  namespace: {{ template "kube-service-selectors.namespace" . }}
  labels:
    {{- include "kube-service-selectors.labels" . | indent 4 }}
  annotations:
    prometheus.io/path: "/"  # scrape path
    {{- if .Values.prometheusScrape }}
    prometheus.io/scrape: "{{ .Values.prometheusScrape }}"
    {{- end }}
    {{- if .Values.service.annotations }}
    {{- toYaml .Values.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.port | default 8080 }}
      protocol: TCP
      name: "http"
    {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.clusterIP }}
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- end }}
  selector:
    {{- include "kube-service-selectors.selectorLabels" . | indent 4 }}
